In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
file_list = [f'../regenie_output/PCa_ukb_step2_BT.chr{i}_PCa.regenie' for i in range(1,23)]

In [3]:
merged = pd.DataFrame()
for i in range(0,22):
    print(f'Reading Chromosome {""*len(str(i+1))}{i+1} statsfile')
    merged = merged.append(pd.read_csv(file_list[i], sep=' '))

Reading Chromosome 1 statsfile
Reading Chromosome 2 statsfile
Reading Chromosome 3 statsfile
Reading Chromosome 4 statsfile
Reading Chromosome 5 statsfile
Reading Chromosome 6 statsfile
Reading Chromosome 7 statsfile
Reading Chromosome 8 statsfile
Reading Chromosome 9 statsfile
Reading Chromosome 10 statsfile
Reading Chromosome 11 statsfile
Reading Chromosome 12 statsfile
Reading Chromosome 13 statsfile
Reading Chromosome 14 statsfile
Reading Chromosome 15 statsfile
Reading Chromosome 16 statsfile
Reading Chromosome 17 statsfile
Reading Chromosome 18 statsfile
Reading Chromosome 19 statsfile
Reading Chromosome 20 statsfile
Reading Chromosome 21 statsfile
Reading Chromosome 22 statsfile

In [4]:
merged

,CHROM,GENPOS,ID,ALLELE0,ALLELE1,A1FREQ,INFO,N,TEST,BETA,SE,CHISQ,LOG10P
0,1,10177,rs367896724,A,AC,0.399127,0.465874,181551,ADD,0.043175,0.025688,2.824780,1.032360
1,1,10235,rs540431307,T,TA,0.000336,0.189403,181551,ADD,-0.116427,1.135970,0.010504,0.036984
2,1,10352,rs201106462,T,TA,0.392646,0.443736,181551,ADD,0.034425,0.026035,1.748320,0.730281
3,1,10511,rs534229142,G,A,0.001253,0.438292,181551,ADD,0.529827,0.356864,2.204260,0.861287
4,1,10539,rs537182016,C,A,0.000508,0.178469,181551,ADD,1.034390,0.858804,1.450710,0.641277
...,...,...,...,...,...,...,...,...,...,...,...,...,...
830721,22,51241102,rs533336397,T,C,0.000157,0.268413,181551,ADD,-0.583526,1.221240,0.228308,0.198746
830722,22,51241285,rs7287738,T,G,0.000593,0.125876,181551,ADD,0.670775,0.993029,0.456278,0.301579
830723,22,51241386,rs568168135,C,G,0.009377,0.389850,181551,ADD,0.251821,0.142152,3.138180,1.116460
830724,22,51244163,rs199560686,A,G,0.000035,0.146007,181551,ADD,-0.153899,0.979922,0.024666,0.057891
830725,22,51244237,rs575160859,C,T,0.013080,0.494355,181551,ADD,0.052834,0.105632,0.250171,0.209747

In [5]:
merged.to_csv('../PCa_ukb_step2_BT.regenie', sep=' ', index=False)